### ISSUE TITLE
Relation "jacl2_rights" does not exist when trying to use lizmap with PostgreSQL

### ISSUE THREAD

**Issue by kevincote** [jancelin/docker-lizmap#35]
I'm trying to use postgresql to store user data for lizmap. Here is my compose file:

```
version: '3.2'
services:
  lizmap:
    image: kevincote/docker-lizmap-3-1-4
    container_name: lizmap
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - type: volume
       source: /c/Users/kevin.cote/Desktop/liz/web/projects
       target: /home
     - type: volume
       source: /c/Users/kevin.cote/Desktop/liz/web/tmp
       target: /tmp
     - type: volume
       source: /c/Users/kevin.cote/Desktop/liz/web/var
       target: /var/www/websig/lizmap/var
    links:
     - qgiserver
     - postgres_auth
     - postgres_logs

  qgiserver:
    image: jancelin/qgis-server:2.18-wfsOutputExtension
    container_name: qgiserver
    restart: always
    volumes:
      - /c/Users/kevin.cote/Desktop/liz/web/projects:/home
    expose:
      - 80

  postgres_auth:
    image: postgres:9.4.15
    container_name: pgsql-auth
    restart: always
    environment:
      POSTGRES_USER: lizauth
      POSTGRES_PASSWORD: 12345

  postgres_logs:
    image: postgres:9.4.15
    container_name: pgsql-logs
    restart: always
    environment:
      POSTGRES_USER: lizlogs
      POSTGRES_PASSWORD: 12345
```

Here is the config inside `profiles.ini.php`:
```
; name of the default profile to use for any connection
default=jauth
jacl2_profile=jauth

;[jdb:jauth]
;driver=sqlite3
;database="var:db/jauth.db"

;[jdb:lizlog]
;driver=sqlite3
;database="var:db/logs.db"

; when you have charset issues, enable force_encoding so the connection will be
; made with the charset indicated in jelix config
;force_encoding = on

; with the following parameter, you can specify a table prefix which will be
; applied to DAOs automatically. For manual jDb requests, please use method
; jDbConnection::prefixTable().
;table_prefix =

; Example for pdo :
;driver=pdo
;dsn=mysql:host=localhost;dbname=test
;user=
;password=

[jdb:jauth]
driver="pgsql"
database="lizauth"
host="postgres_auth"
user="lizauth"
password="12345"

[jdb:lizlog]
driver="pgsql"
database="lizlogs"
host="postgres_logs"
user="lizlogs"
password="12345"
```

After starting the containers, I can't access Lizmap portal (`Error 500. A technical error has occured. Sorry for this trouble.`). If I look at the logs, I have this:

```
2017-12-06 15:12:21	192.168.99.1	error	2017-12-06 15:12:21	[403]	Erreur dans la requête (ERROR:  relation "jacl2_rights" does not exist
LINE 1: ..."id_aclgrp", "r"."id_aclres", "r"."canceled" FROM "jacl2_rig...
                                                             ^(SELECT "r"."id_aclsbj", "r"."id_aclgrp", "r"."id_aclres", "r"."canceled" FROM "jacl2_rights" AS "r" WHERE  "r"."id_aclres" = '-' AND "r"."id_aclgrp" = '__anonymous'))	/var/www/websig/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	165
```

When connecting to the postgresql databases, I don't see any tables inside it. I guess that the table weren't initiated. 

I tried to solve this issue by re-executing the installer.php file inside the install dir in the lizmap container, without success. I also tried to modify the `setup.sh` file to use a `profiles.ini.php` file with already modified database configuration for postgresql, but it gave me the same error message.

Any idea what I am doing wrong ?
