### ISSUE TITLE
Containeur se lance mais impossible de se connecter

### ISSUE THREAD

**Issue by Doctor-Who** [jancelin/docker-lizmap#44]
Bonjour,

- Serveur DELL PowerEdge R630
- openSUSE 42.3 64 bits
- Docker version | 17.09.1-ce
- Docker-compose version | 1.17.0
- CPU | 56
- Memory | 135.1 GB

Contenu du fichier docker-compose.yml :
```
version: '3.4'
services:

  lizmap:
    image: jancelin/docker-lizmap:latest
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - /srv/data/lizmap_project:/home
     - /srv/data/lizmap_var:/var/www/websig/lizmap/var
     - /srv/data/tmp:/tmp
    links:
     - qgiserver:qgiserver

  qgiserver:
    image: jancelin/qgis-server:2.18-wfsOutputExtension
    restart: always
    volumes:
      - /srv/data/lizmap_project:/home
    expose:
      - 80
```
J'accède bien à la page d'accueil (vide) de lizmap
Connexion à l'admin impossible avec id : admin / pass : admin 
Aucun message d'erreur, rien, la page se recharge mais rien ne se passe et je ne suis pas connecté (testé avec firefox, chromium en mode normal et navigation privée juste au cas où)
J'ai essayé de saisir un autre utilisateur au hasard : lizmap me répond bien que l'authentification est incorrecte

Au cas où ce serait du à ma distribution exotique, j'ai réessayé en commentant l'ensemble des volumes pour écarter tout problème de droits et ne fonctionner qu'avec des données interne (même si un `chown -R 33:33 /srv/data/lizmap_project /srv/data/lizmap_var /srv/data/tmp` est censé résoudre le problème)

Quand j'entre en commande dans le container (via portainer par ex), je parcours bien depuis le containeur les projets et fichiers QGIS ajouté depuis mon hôte openSUSE mais lizmap ne voit rien hélas (ni projet, pas de login possible)

J'espère que ces infos complètes vous permettrons de me filer un coup de main :)
